"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STR_CONTENT = "content";
exports.STR_VERTICAL = "vertical";
exports.STR_HORIZONTAL = "horizontal";
exports.STR_PREFERRED = "preferred";
exports.STR_GRID = "grid";
exports.FIXED_TOP = "fixed-top";
exports.FIXED_LEFT = "fixed-left";
exports.FIXED_RIGHT = "fixed-right";
exports.FIXED_BOTTOM = "fixed-bottom";
exports.FIXED_BOTH = "fixed-both";
exports.SIZE_FIXED = "size-fixed";
// オプション文字列　全て小文字 数字を含まない
// OPTION名に H V　X Yといった、高さ方向をしめすものはできるだけ出さないようにする
exports.STYLE_ALIGN = "align"; // テキストの縦横のアライメントの設定が可能　XDの設定に上書き
exports.STYLE_BLANK = "blank";
exports.STYLE_BUTTON = "button";
exports.STYLE_BUTTON_TRANSITION = "button-transition";
exports.STYLE_BUTTON_TRANSITION_TARGET_GRAPHIC = "button-transition-target-graphic";
exports.STYLE_BUTTON_TRANSITION_HIGHLIGHTED_SPRITE_TARGET = "button-transition-highlighted-sprite-target";
exports.STYLE_BUTTON_TRANSITION_PRESSED_SPRITE_TARGET = "button-transition-pressed-sprite-target";
exports.STYLE_BUTTON_TRANSITION_SELECTED_SPRITE_TARGET = "button-transition-selected-sprite-target";
exports.STYLE_BUTTON_TRANSITION_DISABLED_SPRITE_TARGET = "button-transition-disabled-sprite-target";
exports.STYLE_CANVAS_GROUP = "canvas-group"; // 削除予定
exports.STYLE_COMMENT_OUT = "comment-out";
exports.STYLE_COMPONENT = "component";
exports.STYLE_CONTENT_SIZE_FITTER = "content-size-fitter"; //自身のSizeFitterオプション
exports.STYLE_CONTENT_SIZE_FITTER_HORIZONTAL_FIT = "content-size-fitter-horizontal-fit";
exports.STYLE_CONTENT_SIZE_FITTER_VERTICAL_FIT = "content-size-fitter-vertical-fit";
exports.STYLE_MARGIN_FIX = "fix";
exports.STYLE_IMAGE = "image";
exports.STYLE_IMAGE_SCALE = "image-scale";
exports.STYLE_IMAGE_SLICE = "image-slice"; // 9スライス ドット数を指定する
exports.STYLE_IMAGE_TYPE = "image-type"; // sliced/tiled/simple/filled
exports.STYLE_IMAGE_FIT_PARENT_BOUNDS = "image-fit-parent-bounds"; // 親と同じ大きさで画像を作成する
exports.STYLE_LAYER = "layer";
exports.STYLE_LAYOUT_ELEMENT = "layout-element";
exports.STYLE_LAYOUT_ELEMENT_IGNORE_LAYOUT = "layout-element-ignore-layout";
exports.STYLE_LAYOUT_ELEMENT_PREFERRED_WIDTH = "layout-element-preferred-width";
exports.STYLE_LAYOUT_ELEMENT_PREFERRED_HEIGHT = "layout-element-preferred-height";
exports.STYLE_LAYOUT_GROUP = "layout-group"; //子供を自動的にどうならべるかのオプション
exports.STYLE_LAYOUT_GROUP_CHILD_ALIGNMENT = "layout-group-child-alignment";
exports.STYLE_LAYOUT_GROUP_CHILD_FORCE_EXPAND = "layout-group-child-force-expand";
exports.STYLE_LAYOUT_GROUP_CHILD_CONTROL_SIZE = "layout-group-child-control-size";
exports.STYLE_LAYOUT_GROUP_SPACING_X = "layout-group-spacing-x";
exports.STYLE_LAYOUT_GROUP_SPACING_Y = "layout-group-spacing-y";
exports.STYLE_LAYOUT_GROUP_START_AXIS = "layout-group-start-axis";
exports.STYLE_LAYOUT_GROUP_USE_CHILD_SCALE = "layout-group-use-child-scale";
exports.STYLE_MATCH_LOG = "match-log";
exports.STYLE_PRESERVE_ASPECT = "preserve-aspect";
exports.STYLE_LOCK_ASPECT = "lock-aspect"; // preserve-aspectと同じ動作にする　アスペクト比を維持する
exports.STYLE_RAYCAST_TARGET = "raycast-target"; // 削除予定
exports.STYLE_RECT_MASK_2D = "rect-mask-twod";
exports.STYLE_RECT_TRANSFORM_ANCHOR_OFFSET_X = "rect-transform-anchor-offset-x"; // offset-min offset-max anchors-min anchors-maxの順
exports.STYLE_RECT_TRANSFORM_ANCHOR_OFFSET_Y = "rect-transform-anchor-offset-y"; // offset-min offset-max anchors-min anchors-maxの順
exports.STYLE_RECT_TRANSFORM_ANCHORS_X = "rect-transform-anchors-x"; // anchors-min anchors-maxの順
exports.STYLE_RECT_TRANSFORM_ANCHORS_Y = "rect-transform-anchors-y"; // anchors-min anchors-maxの順
exports.STYLE_REPEATGRID_ATTACH_TEXT_DATA_SERIES = "repeatgrid-attach-text-data-series";
exports.STYLE_REPEATGRID_ATTACH_IMAGE_DATA_SERIES = "repeatgrid-attach-image-data-series";
exports.STYLE_SCROLLBAR = "scrollbar";
exports.STYLE_SCROLLBAR_DIRECTION = "scrollbar-direction";
exports.STYLE_SCROLLBAR_HANDLE_TARGET = "scrollbar-handle-target";
exports.STYLE_SCROLL_RECT = "scroll-rect";
exports.STYLE_SCROLL_RECT_CONTENT_NAME = "scroll-rect-content-target";
exports.STYLE_SCROLL_RECT_HORIZONTAL_SCROLLBAR_TARGET = "scroll-rect-horizontal-scrollbar-target";
exports.STYLE_SCROLL_RECT_VERTICAL_SCROLLBAR_TARGET = "scroll-rect-vertical-scrollbar-target";
exports.STYLE_SLIDER = "slider";
exports.STYLE_SLIDER_DIRECTION = "slider-direction";
exports.STYLE_SLIDER_FILL_RECT_TARGET = "slider-fill-rect-target";
exports.STYLE_SLIDER_HANDLE_RECT_TARGET = "slider-handle-rect-target";
exports.STYLE_TEXT = "text";
exports.STYLE_TEXTMP = "textmp"; // textmeshpro
exports.STYLE_TEXT_STRING = "text-string";
exports.STYLE_TOGGLE = "toggle";
exports.STYLE_TOGGLE_TRANSITION = "toggle-transition";
exports.STYLE_TOGGLE_GRAPHIC_TARGET = "toggle-graphic-target";
exports.STYLE_TOGGLE_TRANSITION_TARGET_GRAPHIC_TARGET = "toggle-transition-target-graphic-target";
exports.STYLE_TOGGLE_TRANSITION_HIGHLIGHTED_SPRITE_TARGET = "toggle-transition-highlighted-sprite-target";
exports.STYLE_TOGGLE_TRANSITION_PRESSED_SPRITE_TARGET = "toggle-transition-pressed-sprite-target";
exports.STYLE_TOGGLE_TRANSITION_SELECTED_SPRITE_TARGET = "toggle-transition-selected-sprite-target";
exports.STYLE_TOGGLE_TRANSITION_DISABLED_SPRITE_TARGET = "toggle-transition-disabled-sprite-target";
exports.STYLE_TOGGLE_GROUP = "toggle-group";
exports.STYLE_INPUT = "input";
exports.STYLE_INPUT_TRANSITION = "input-transition";
exports.STYLE_INPUT_GRAPHIC_NAME = "input-graphic-target";
exports.STYLE_INPUT_TARGET_GRAPHIC_NAME = "input-transition-target-graphic-target";
exports.STYLE_INPUT_TRANSITION_HIGHLIGHTED_SPRITE_TARGET = "input-transition-highlighted-sprite-target";
exports.STYLE_INPUT_TRANSITION_PRESSED_SPRITE_TARGET = "input-transition-pressed-sprite-target";
exports.STYLE_INPUT_TRANSITION_SELECTED_SPRITE_TARGET = "input-transition-selected-sprite-target";
exports.STYLE_INPUT_TRANSITION_DISABLED_SPRITE_TARGET = "input-transition-disabled-sprite-target";
exports.STYLE_INPUT_TEXT_TARGET = "input-text-target";
exports.STYLE_INPUT_PLACEHOLDER_TARGET = "input-placeholder-target";
exports.STYLE_CREATE_CONTENT = "create-content";
exports.STYLE_CREATE_CONTENT_BOUNDS = "create-content-bounds";
exports.STYLE_CREATE_CONTENT_NAME = "create-content-name";
exports.STYLE_V_ALIGN = "v-align"; //テキストの縦方向のアライメント XDの設定に追記される
exports.STYLE_ADD_COMPONENT = "add-component";
exports.STYLE_MASK = "mask";
exports.STYLE_UNITY_NAME = "unity-name";
exports.STYLE_CHECK_LOG = "check-log";
